#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.CAP.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\WebMessage.cshtml"
    using DotNetCore.CAP.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\WebMessage.cshtml"
    using DotNetCore.CAP.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class WebMessage : DotNetCore.CAP.Dashboard.RazorPage
    {
#line hidden

        protected override void Execute()
        {


WriteLiteral("\r\n");





            
            #line 5 "..\..\Dashboard\Pages\WebMessage.cshtml"
  
    Layout = new LayoutPage(Strings.WebMessage_Manage);


            
            #line default
            #line hidden
WriteLiteral("<div class=\"row\">\r\n    <div class=\"col-md-12\">\r\n        <h1 class=\"page-header\">");


            
            #line 10 "..\..\Dashboard\Pages\WebMessage.cshtml"
                           Write(Strings.WebMessage_Manage);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n        <div class=\"btn-toolbar btn-toolbar-top\">\r\n            <button cla" +
"ss=\"btn btn-sm btn-primary webMessageModal\"\r\n                    data-current=\"{" +
"}\"\r\n                    data-url=\"");


            
            #line 14 "..\..\Dashboard\Pages\WebMessage.cshtml"
                         Write(Url.To("/webmessage/save"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                    data-loading-text=\"");


            
            #line 15 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                   Write(Strings.WebMessage_Add);

            
            #line default
            #line hidden
WriteLiteral("...\">\r\n                <span class=\"glyphicon glyphicon-plus\"></span>\r\n          " +
"      ");


            
            #line 17 "..\..\Dashboard\Pages\WebMessage.cshtml"
           Write(Strings.WebMessage_Add);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </button>\r\n        </div>\r\n\r\n");


            
            #line 21 "..\..\Dashboard\Pages\WebMessage.cshtml"
         if (WebMessages.Count() == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\r\n                ");


            
            #line 24 "..\..\Dashboard\Pages\WebMessage.cshtml"
           Write(Strings.WebMessage_NoData);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 26 "..\..\Dashboard\Pages\WebMessage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"table-responsive\">\r\n                <table class=\"table s" +
"ubscribe-table\">\r\n                    <thead>\r\n                        <tr>\r\n   " +
"                         <th width=\"20%\">");


            
            #line 33 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                       Write(Strings.Common_Group);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th width=\"30%\">");


            
            #line 34 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                       Write(Strings.Common_Name);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th>");


            
            #line 35 "..\..\Dashboard\Pages\WebMessage.cshtml"
                           Write(Strings.Common_ApiUrl);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th>");


            
            #line 36 "..\..\Dashboard\Pages\WebMessage.cshtml"
                           Write(Strings.Common_Opt);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        </tr>\r\n                    </thead>\r\n             " +
"       <tbody>\r\n\r\n");


            
            #line 41 "..\..\Dashboard\Pages\WebMessage.cshtml"
                         foreach (var message in WebMessages)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>");


            
            #line 44 "..\..\Dashboard\Pages\WebMessage.cshtml"
                               Write(message.Group);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");


            
            #line 45 "..\..\Dashboard\Pages\WebMessage.cshtml"
                               Write(message.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");


            
            #line 46 "..\..\Dashboard\Pages\WebMessage.cshtml"
                               Write(message.Url);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>\r\n                                    " +
"<button class=\"js-webmessage-command btn btn-sm btn-success\" data-url=\"");


            
            #line 48 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                                       Write(Url.To("/webmessage/run/") + message.Id);

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 48 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                                                                                                      Write(Strings.Common_Start);

            
            #line default
            #line hidden
WriteLiteral("...\">\r\n                                        <span class=\"glyphicon glyphicon-p" +
"lay-circle\"></span> ");


            
            #line 49 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                         Write(Strings.Common_Start);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </button>\r\n                                " +
"    <button class=\"btn btn-sm btn-primary webMessageModal\" data-current=\"");


            
            #line 51 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                                    Write(message.ToJsonString());

            
            #line default
            #line hidden
WriteLiteral("\" data-url=\"");


            
            #line 51 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                                                                       Write(Url.To("/webmessage/save"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                        <span class=\"glyphicon glyphicon-cog\"" +
"></span> ");


            
            #line 52 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                 Write(Strings.Common_Edit);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </button>\r\n                                " +
"    <button class=\"js-webmessage-command btn btn-sm btn-primary\" data-url=\"");


            
            #line 54 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                                       Write(Url.To("/webmessage/delete/") + message.Id);

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 54 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                                                                                                         Write(Strings.Common_Delete);

            
            #line default
            #line hidden
WriteLiteral("...\">\r\n                                        <span class=\"glyphicon glyphicon-t" +
"rash\"></span> ");


            
            #line 55 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                   Write(Strings.Common_Delete);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </button>\r\n                                " +
"</td>\r\n                            </tr>\r\n");


            
            #line 59 "..\..\Dashboard\Pages\WebMessage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n            </div>\r\n");


            
            #line 63 "..\..\Dashboard\Pages\WebMessage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral(@"
        <div>
            <div class=""modal fade"" tabindex=""-1"" role=""dialog"">
                <div class=""modal-dialog"" role=""document"">
                    <div class=""modal-content"">
                        <div class=""modal-header"">
                            <button type=""button"" class=""close"" data-dismiss=""modal"" aria-label=""Close"">
                                <span aria-hidden=""true"">&times;</span>
                            </button>
                            <h4 class=""modal-title"">Web Message</h4>
                        </div>
                        <div id=""jsonContent"" style=""max-height: 500px; overflow-y: auto;"" class=""modal-body"">
                            <form class=""row"">
                                <div class=""col-md-12 form-group"">
                                    <input type=""text"" class=""form-control"" name=""group"" placeholder=""");


            
            #line 78 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                                 Write(Strings.WebMessage_Edit_Group);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                                </div>\r\n                                <di" +
"v class=\"col-md-12 form-group\">\r\n                                    <input type" +
"=\"text\" class=\"form-control\" name=\"name\" placeholder=\"");


            
            #line 81 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                                Write(Strings.WebMessage_Edit_Name);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                                </div>\r\n\r\n                                <" +
"div class=\"col-md-12 form-group\">\r\n                                    <input ty" +
"pe=\"text\" class=\"form-control\" name=\"url\" placeholder=\"");


            
            #line 85 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                               Write(Strings.WebMessage_Edit_Url);

            
            #line default
            #line hidden
WriteLiteral(@""" />
                                </div>
                                <div class=""col-md-12 form-group"">
                                    <select id=""webmessage_method"" class=""form-control"">
                                        <option value=""GET"" selected="""">GET</option>
                                        <option value=""POST"">POST</option>
                                        <option value=""PUT"">PUT</option>
                                        <option value=""PATCH"">PATCH</option>
                                        <option value=""DELETE"">DELETE</option>
                                        <option value=""COPY"">COPY</option>
                                        <option value=""HEAD"">HEAD</option>
                                        <option value=""OPTIONS"">OPTIONS</option>
                                        <option value=""LINK"">LINK</option>
                                        <option value=""UNLINK"">UNLINK</option>
                                        <option value=""PURGE"">PURGE</option>
                                    </select>
                                </div>
                                <div class=""col-md-12 form-group"">
                                    <textarea class=""form-control"" id=""webmessage_headers"" rows=""3"" placeholder=""");


            
            #line 103 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                                            Write(Strings.WebMessage_Edit_Headers);

            
            #line default
            #line hidden
WriteLiteral("\"></textarea>\r\n                                </div>\r\n                          " +
"      <div class=\"col-md-12 form-group\">\r\n                                    <t" +
"extarea class=\"form-control\" id=\"webmessage_content\" rows=\"3\" placeholder=\"");


            
            #line 106 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                                            Write(Strings.WebMessage_Edit_Content);

            
            #line default
            #line hidden
WriteLiteral(@"""></textarea>
                                </div>
                            </form>
                        </div>
                        <div class=""modal-footer"">
                            <button type=""button"" class=""btn btn-sm btn-primary"" id=""webMessageSaveBtn"">");


            
            #line 111 "..\..\Dashboard\Pages\WebMessage.cshtml"
                                                                                                   Write(Strings.WebMessage_Save);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                        </div>\r\n                    </div><!-- /.modal" +
"-content -->\r\n                </div><!-- /.modal-dialog -->\r\n            </div><" +
"!-- /.modal -->\r\n        </div>\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
