//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.CAP.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetCore.CAP.Dashboard.Content.resx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 API 的本地化字符串。
        /// </summary>
        public static string Common_ApiUrl {
            get {
                return ResourceManager.GetString("Common_ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created 的本地化字符串。
        /// </summary>
        public static string Common_Created {
            get {
                return ResourceManager.GetString("Common_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete selected 的本地化字符串。
        /// </summary>
        public static string Common_DeleteSelected {
            get {
                return ResourceManager.GetString("Common_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting... 的本地化字符串。
        /// </summary>
        public static string Common_Deleting {
            get {
                return ResourceManager.GetString("Common_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueued 的本地化字符串。
        /// </summary>
        public static string Common_Enqueued {
            get {
                return ResourceManager.GetString("Common_Enqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueueing... 的本地化字符串。
        /// </summary>
        public static string Common_Enqueueing {
            get {
                return ResourceManager.GetString("Common_Enqueueing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetched 的本地化字符串。
        /// </summary>
        public static string Common_Fetched {
            get {
                return ResourceManager.GetString("Common_Fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        public static string Common_Group {
            get {
                return ResourceManager.GetString("Common_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string Common_Id {
            get {
                return ResourceManager.GetString("Common_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Less details... 的本地化字符串。
        /// </summary>
        public static string Common_LessDetails {
            get {
                return ResourceManager.GetString("Common_LessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method 的本地化字符串。
        /// </summary>
        public static string Common_Method {
            get {
                return ResourceManager.GetString("Common_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More details... 的本地化字符串。
        /// </summary>
        public static string Common_MoreDetails {
            get {
                return ResourceManager.GetString("Common_MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N/A 的本地化字符串。
        /// </summary>
        public static string Common_NotAvailable {
            get {
                return ResourceManager.GetString("Common_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Common_Opt {
            get {
                return ResourceManager.GetString("Common_Opt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        public static string Common_PeriodDay {
            get {
                return ResourceManager.GetString("Common_PeriodDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Week 的本地化字符串。
        /// </summary>
        public static string Common_PeriodWeek {
            get {
                return ResourceManager.GetString("Common_PeriodWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reason 的本地化字符串。
        /// </summary>
        public static string Common_Reason {
            get {
                return ResourceManager.GetString("Common_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReExecution 的本地化字符串。
        /// </summary>
        public static string Common_ReConsume {
            get {
                return ResourceManager.GetString("Common_ReConsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requeue messages 的本地化字符串。
        /// </summary>
        public static string Common_RequeueMessages {
            get {
                return ResourceManager.GetString("Common_RequeueMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry 的本地化字符串。
        /// </summary>
        public static string Common_Retry {
            get {
                return ResourceManager.GetString("Common_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        public static string Common_Server {
            get {
                return ResourceManager.GetString("Common_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Common_Start {
            get {
                return ResourceManager.GetString("Common_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        public static string Common_State {
            get {
                return ResourceManager.GetString("Common_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string Common_Unknown {
            get {
                return ResourceManager.GetString("Common_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string Common_Version {
            get {
                return ResourceManager.GetString("Common_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish Failed 的本地化字符串。
        /// </summary>
        public static string HomePage_GraphHover_PFailed {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_PFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish Succeeded 的本地化字符串。
        /// </summary>
        public static string HomePage_GraphHover_PSucceeded {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_PSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consumption Failed 的本地化字符串。
        /// </summary>
        public static string HomePage_GraphHover_RFailed {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_RFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consumption Succeeded 的本地化字符串。
        /// </summary>
        public static string HomePage_GraphHover_RSucceeded {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_RSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 24h graph 的本地化字符串。
        /// </summary>
        public static string HomePage_HistoryGraph {
            get {
                return ResourceManager.GetString("HomePage_HistoryGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Realtime graph 的本地化字符串。
        /// </summary>
        public static string HomePage_RealtimeGraph {
            get {
                return ResourceManager.GetString("HomePage_RealtimeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard 的本地化字符串。
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to site 的本地化字符串。
        /// </summary>
        public static string LayoutPage_Back {
            get {
                return ResourceManager.GetString("LayoutPage_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generated: {0}ms 的本地化字符串。
        /// </summary>
        public static string LayoutPage_Footer_Generatedms {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Generatedms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node: {0} 的本地化字符串。
        /// </summary>
        public static string LayoutPage_Footer_NodeCurrent {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_NodeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time: 的本地化字符串。
        /// </summary>
        public static string LayoutPage_Footer_Time {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Modal_Expand {
            get {
                return ResourceManager.GetString("MessagesPage_Modal_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Modal_Format {
            get {
                return ResourceManager.GetString("MessagesPage_Modal_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raw 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Modal_Raw {
            get {
                return ResourceManager.GetString("MessagesPage_Modal_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collaspse 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Model_Collaspse {
            get {
                return ResourceManager.GetString("MessagesPage_Model_Collaspse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No messages found. 的本地化字符串。
        /// </summary>
        public static string MessagesPage_NoMessages {
            get {
                return ResourceManager.GetString("MessagesPage_NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Query_Button {
            get {
                return ResourceManager.GetString("MessagesPage_Query_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message body 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Query_MessageBody {
            get {
                return ResourceManager.GetString("MessagesPage_Query_MessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message group 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Query_MessageGroup {
            get {
                return ResourceManager.GetString("MessagesPage_Query_MessageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message name 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Query_MessageName {
            get {
                return ResourceManager.GetString("MessagesPage_Query_MessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Table_Code {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expries At 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Table_ExpiresAt {
            get {
                return ResourceManager.GetString("MessagesPage_Table_ExpiresAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Table_Group {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Table_Name {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retries 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Table_Retries {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        public static string MessagesPage_Table_State {
            get {
                return ResourceManager.GetString("MessagesPage_Table_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueued 的本地化字符串。
        /// </summary>
        public static string Metrics_EnqueuedCountOrNull {
            get {
                return ResourceManager.GetString("Metrics_EnqueuedCountOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueued / Queues 的本地化字符串。
        /// </summary>
        public static string Metrics_EnqueuedQueuesCount {
            get {
                return ResourceManager.GetString("Metrics_EnqueuedQueuesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} failed message(s) found.  的本地化字符串。
        /// </summary>
        public static string Metrics_FailedCountOrNull {
            get {
                return ResourceManager.GetString("Metrics_FailedCountOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Servers 的本地化字符串。
        /// </summary>
        public static string Metrics_Servers {
            get {
                return ResourceManager.GetString("Metrics_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Connections 的本地化字符串。
        /// </summary>
        public static string Metrics_TotalConnections {
            get {
                return ResourceManager.GetString("Metrics_TotalConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Published 的本地化字符串。
        /// </summary>
        public static string NavigationMenu_Published {
            get {
                return ResourceManager.GetString("NavigationMenu_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received 的本地化字符串。
        /// </summary>
        public static string NavigationMenu_Received {
            get {
                return ResourceManager.GetString("NavigationMenu_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Servers 的本地化字符串。
        /// </summary>
        public static string NavigationMenu_Servers {
            get {
                return ResourceManager.GetString("NavigationMenu_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscribers 的本地化字符串。
        /// </summary>
        public static string NavigationMenu_Subscribers {
            get {
                return ResourceManager.GetString("NavigationMenu_Subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no config distributed node discory 的本地化字符串。
        /// </summary>
        public static string NodePage_NoNodes {
            get {
                return ResourceManager.GetString("NodePage_NoNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch 的本地化字符串。
        /// </summary>
        public static string NodePage_Switch {
            get {
                return ResourceManager.GetString("NodePage_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP Address 的本地化字符串。
        /// </summary>
        public static string NodePage_Table_IP {
            get {
                return ResourceManager.GetString("NodePage_Table_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node Name 的本地化字符串。
        /// </summary>
        public static string NodePage_Table_NodeName {
            get {
                return ResourceManager.GetString("NodePage_Table_NodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string NodePage_Table_Port {
            get {
                return ResourceManager.GetString("NodePage_Table_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nodes 的本地化字符串。
        /// </summary>
        public static string NodePage_Title {
            get {
                return ResourceManager.GetString("NodePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Paginator_Next {
            get {
                return ResourceManager.GetString("Paginator_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prev 的本地化字符串。
        /// </summary>
        public static string Paginator_Prev {
            get {
                return ResourceManager.GetString("Paginator_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total items 的本地化字符串。
        /// </summary>
        public static string Paginator_TotalItems {
            get {
                return ResourceManager.GetString("Paginator_TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items per page 的本地化字符串。
        /// </summary>
        public static string PerPageSelector_ItemsPerPage {
            get {
                return ResourceManager.GetString("PerPageSelector_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Published Messages 的本地化字符串。
        /// </summary>
        public static string PublishedMessagesPage_Title {
            get {
                return ResourceManager.GetString("PublishedMessagesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Published messages 的本地化字符串。
        /// </summary>
        public static string PublishedPage_Title {
            get {
                return ResourceManager.GetString("PublishedPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received Messages 的本地化字符串。
        /// </summary>
        public static string ReceivedMessagesPage_Title {
            get {
                return ResourceManager.GetString("ReceivedMessagesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received Messages 的本地化字符串。
        /// </summary>
        public static string ReceivedPage_Title {
            get {
                return ResourceManager.GetString("ReceivedPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string SidebarMenu_Failed {
            get {
                return ResourceManager.GetString("SidebarMenu_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeeded 的本地化字符串。
        /// </summary>
        public static string SidebarMenu_Succeeded {
            get {
                return ResourceManager.GetString("SidebarMenu_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no config CAP subscribers. 的本地化字符串。
        /// </summary>
        public static string SubscribersPage_NoSubscribers {
            get {
                return ResourceManager.GetString("SubscribersPage_NoSubscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscribers 的本地化字符串。
        /// </summary>
        public static string SubscribersPage_Title {
            get {
                return ResourceManager.GetString("SubscribersPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string WebMessage_Add {
            get {
                return ResourceManager.GetString("WebMessage_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string WebMessage_Edit_Content {
            get {
                return ResourceManager.GetString("WebMessage_Edit_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        public static string WebMessage_Edit_Group {
            get {
                return ResourceManager.GetString("WebMessage_Edit_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Headers 的本地化字符串。
        /// </summary>
        public static string WebMessage_Edit_Headers {
            get {
                return ResourceManager.GetString("WebMessage_Edit_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method 的本地化字符串。
        /// </summary>
        public static string WebMessage_Edit_Method {
            get {
                return ResourceManager.GetString("WebMessage_Edit_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string WebMessage_Edit_Name {
            get {
                return ResourceManager.GetString("WebMessage_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url 的本地化字符串。
        /// </summary>
        public static string WebMessage_Edit_Url {
            get {
                return ResourceManager.GetString("WebMessage_Edit_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebMessage 的本地化字符串。
        /// </summary>
        public static string WebMessage_Manage {
            get {
                return ResourceManager.GetString("WebMessage_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no config CAP webmessage. 的本地化字符串。
        /// </summary>
        public static string WebMessage_NoData {
            get {
                return ResourceManager.GetString("WebMessage_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string WebMessage_Save {
            get {
                return ResourceManager.GetString("WebMessage_Save", resourceCulture);
            }
        }
    }
}
